### ISSUE TITLE
src/libxsmm_trace.c: 3 * off by one error ?

### ISSUE THREAD

**Issue by dcb314** [libxsmm/libxsmm#616]
Static analyser cppcheck says:

src/libxsmm_trace.c:129:18: error: Width 32 given in format string (no. 1) is larger than destination buffer 'buffer[32]', use %31[^,] to prevent overflowing it. [invalidScanfFormatWidth]
src/libxsmm_trace.c:132:18: error: Width 32 given in format string (no. 1) is larger than destination buffer 'buffer[32]', use %31[^,] to prevent overflowing it. [invalidScanfFormatWidth]
src/libxsmm_trace.c:135:18: error: Width 32 given in format string (no. 1) is larger than destination buffer 'buffer[32]', use %31s to prevent overflowing it. [invalidScanfFormatWidth]

**Comment by hfp** [comment]
I have checked with cppcheck v2.3 (Debian/stable) and v2.7 (latest), and cannot reproduce this report using LIBXSMM/master. Is your report based on a specific version/release of LIBXSMM?

**Comment by hfp** [comment]
> I use the trunk version of cppcheck and the --force flag. The second of these is probably
all you need to reproduce it.

I also used the `--force` flag in both cases (v2.3 and v2.7). It seems this is to run "unlimited configurations" (in cppcheck's nomenclature). The latter is basically all combinations of compile-time code-path possible as per `-D` preprocessor definitions discovered for a translation unit.

I think I have to compile/use the trunk version of cppcheck.

**Comment by dcb314** [comment]
>I think I have to compile/use the trunk version of cppcheck.

I don't think so. Perhaps I was slightly less than clear by using sarcasm earlier,
but I strongly recommend merely looking at the code. By inspection, it is wrong.

I don't understand why you need a tool to confirm an error.

**Comment by hfp** [comment]
I have now used `cppcheck -DLIBXSMM_PLATFORM_X86 -Iinclude --force --enable=all --suppress=unknownMacro --suppress=ConfigurationNotChecked --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=unmatchedSuppression src/libxsmm_trace.c` and I can reproduce your report.

> I don't understand why you need a tool to confirm an error.

Though, the translation unit you refer to is rarely changed (or can be called "legacy" if you want). We aim for a reproducible flow and static analysis of different kinds are already in use (but not `cppcheck`). I am interested to adopt `cppcheck` at least for some manual/occasional analysis. I am otherwise able to comprehend and confirm an error in our source code, but this is a 2nd step. Also, I would be careful calling this an "error" right away even if this code does may not meet "defensive programming" requirements.
