### ISSUE TITLE
Do we have plan to support bias/relu fusion in generated gemm kernel?

### ISSUE THREAD

**Issue by zhuwenxi** [libxsmm/libxsmm#622]
Existing `libxsmm_mmfunction` doesn't support fused-ops like bias/relu, which is probably the most common pattern in deep learning world. Do we have plan to support such kind of codegen in gemm kernel level?

I understand the `libxsmm_dnn_fullyconnected` layer does claim it has support for bias/relu/sigmoid fusion, however when I looked into the code, I found:
1. All these fusions are only supported in "B" format (locked NCNC KCCK), rather than the most common used "L" format;
2. Support for "B" format is naively implemented with if/else clause in block level rather than kernel level.

I can fire a PR to implement this feature, if you don't mind.

**Comment by alheinecke** [comment]
BTW, I found that you are working on an RFC of integrating LIBXSMM into TVM, https://discuss.tvm.apache.org/t/rfc-top-byoc-intel-libxsmm-integration/11688 .
So the TPP concept we are recently putting into master of libxsmm (and essentially retiring/deleting all libxsmm_dnn_* functions) seems to me like a perfect match.
Please check out our latest paper introducing TPP and it's performance advantages: https://arxiv.org/abs/2104.05755

**Comment by alheinecke** [comment]
yes. the my will change to something meaning full and we will move to code into some stand alone repository at some time. However, I my eyes these codes are just examples of what TVM should generate. In my view TVM should only use the small TPP JIT kernels to stitch together an fully connected layer. 

So all the code in op_lib_tpp should be considered more an example of what TVM or MLIR based tools should generate , rather than providing a library that can be called from those. E.g. when you follow the same steps in generating the code inside TVM, you can easily add tanh, GeLU, sigmoid as activation functions. they are all supported, even to fuse with GEMM, but the fullyconnected_tpp example doesn't make use of this as is an example of how to use TPP to build complex deep learning operators. Of course since then only hold small tensor operations (=TPPs) in your hands you could even fuse inside the TVM compiler a pooling or different operation together and free deep learning from the library jail :-)

**Comment by zhuwenxi** [comment]
OK, I get your point that theses "my_" APIs are just examples to demonstrate how low-level libxsmm API like "libxsmm_xmmdispatch()" could be used to implement a FC operator, which should not be directly called in TVM. Make sense to me, thank you.
