### ISSUE TITLE
Clarification for forcing kernels without MKL fallback

### ISSUE THREAD

**Issue by mlohry** [libxsmm/libxsmm#668]
I'm comparing MKL and XSMM for DGEMM, where my dimensions (m,n,k) range from (4, 1e6, 4) to (64, 1e6, 64), i.e. "small" square matrices multiplied by wide ones. Because of the width of matrices B and C, this exceeds the normal thresholds.

Q1) Limited benchmarks show xsmm providing significant benefit over MKL when compiling with a very high threshold on these problem sizes. Is that expected?

Q2) I'm like to force the use of XSMM kernels independent of the threshold when using the header-only build. Docs suggest the mmdispatch calls force JIT usage, but there seems to be a half dozen interfaces to similar functionality. Right now I have an MKL call

```
cblas_dgemm(CblasColMajor, CblasNoTrans, CblasNoTrans, m, n, k, alpha, matrixA, leadimA, matrixB, leadimB, beta, matrixC, leadimC);
```

replaced by
```
       libxsmm_dmmfunction kernel = libxsmm_dmmdispatch(
            m, n, k, NULL, NULL, NULL, &alpha, &beta, NULL, NULL);
        kernel(matrixA, matrixB, matrixC);
```

As I understand it, this should force the use of xsmm's kernels, is that correct? Are the JIT kernels of this type cached? Typically I'll have maybe 5 different GEMM sizes over the lifetime of the application, none of which are batched.

Q3) What is the difference between that call, and this?
```
typedef libxsmm_mmfunction<T_Double> kernel_type;
         kernel_type kernel(LIBXSMM_GEMM_FLAG_NONE, m, n, k, alpha, beta);
         kernel(matrixA, matrixB, matrixC);
```

Q4) This is in the context of an MPI application where each process should be using a single thread. Will the `dmmdispatch` calls always result in single threaded calls?

Thanks!

**Comment by hfp** [comment]
> Q1) Limited benchmarks show xsmm providing significant benefit over MKL when compiling with a very high threshold on these problem sizes. Is that expected?

The threshold applies only to "high-level" functions like `libxsmm_dgemm` which implement an internal fallback for anything exceeding the threshold or for unsupported cases. This is useful behavior since `libxsmm_dgemm` can act as replacement for `dgemm`. Of course, everything said applies to the single-precision flavor as well.

Whether this is expected or not was not clear before your report. Your input is welcome! Also, I can take a look at your input sizes independently.

> Q2) I'm like to force the use of XSMM kernels independent of the threshold when using the header-only build. Docs suggest the mmdispatch calls force JIT usage, but there seems to be a half dozen interfaces to similar functionality. Right now I have an MKL call

Indeed, dispatching a kernel using any of the "mmdispatch" functions is not subject to a threshold. The "half dozen interfaces to similar functionality" are about to be revised. We are still working towards our next major release 2.0 but documentation refers to our current latest release 1.17 (1.x line).

Perhaps you can share some background on the purpose of your cases and we can of course navigate you through the interfaces for the time being.

> As I understand it, this should force the use of xsmm's kernels, is that correct?

Yes.

> Are the JIT kernels of this type cached?

Yes.

> Typically I'll have maybe 5 different GEMM sizes over the lifetime of the application, none of which are batched.

That's fine (non-batched). If you are able to identify your case in every situation, you can also safe the dispatch overhead (10's of nanoseconds) by tabulating the function pointers on your own. Of course, if your five (or whatever) cases are only known by "MNK, etc" you better rely on LIBXSMM to perform this query. Though, "first time dispatch" (code generation) takes in the order of 10's of microseconds, dispatching from the registry (cold) can take about 100 nanoseconds, and hot dispatch (from a recurring set of 10's of kernels) takes about 10's of nanoseconds on contemporary CPU cores.

**Comment by mlohry** [comment]
Thanks @hfp . My use case is essentially equivalent to @FreddieWitherden 's. For GEMMs of size (m,n,k), n is typically large (>5000) and 1 <= m=k <= 100. There are O(10) specific dimensions throughout execution, each called O(billions) of times so the first time dispatch cost doesn't matter. The hot dispatch cost probably doesn't matter either, as I'm seeing 100-1000 microseconds per call.

I ran some benchmarks for problems of this size with the dmmdispatch vs MKL. This is on one core of a Xeon Platinum 9242. The left is the use case I'm more interested in with n=5000; with m=k < 12 or so xsmm does quite well, with no advantage above that. The right is with n=64 and we see the expected benefit from xsmm through the whole range.

![image](https://user-images.githubusercontent.com/2199374/178815289-c0c4ef0c-a01a-49bd-aa8a-b3c3b87c00c6.png)

Very different result on an AMD EPYC, although that's mostly due to MKL's abysmal performance:

![image](https://user-images.githubusercontent.com/2199374/178815986-bf00768b-3ed3-43d9-b81a-acda89a19a15.png)


Now the normal mode of execution is using MPI with 1 rank per physical core. Running the same benchmark but in MPI on dual socket systems, so every core is doing (m,5000,k) GEMMs simultaneously:

![image](https://user-images.githubusercontent.com/2199374/178817978-5a0d8db1-2da3-4743-ad6e-8e659f41cb61.png)

In that configuration xsmm is performing significantly worse than MKL on the xeons, but perfectly content on the epycs.

**Comment by alheinecke** [comment]
For the PyFR case, we pulled the N loop outside of the kernel, as we block internally over N and M:
https://github.com/libxsmm/libxsmm/blob/master/src/libxsmm_fsspmdm.c#L458
That should help here as well, so it would be great if you could try this.

**Comment by alheinecke** [comment]
Since you output matrices in case of 32 an bigger are much bigger than the L2 / LLC you might want to turn on NTS if beta=0:
https://github.com/libxsmm/libxsmm/blob/master/include/libxsmm_typedefs.h#L397
of course, C has to be aligned to a 64byte boundary and needs 64byte accesses, but that avoids doing the RFOs on C.

**Comment by FreddieWitherden** [comment]
You can try the fsspmdm functions which should do a reasonable job.  Although, really, you want to do what we did in PyFR and cache block your data structure (https://ui.adsabs.harvard.edu/abs/2022CoPhC.27108193A/abstract).  The performance uplift is huge and it makes getting good performance from the GEMM's much easier (no need to copy to scratch space, prefetch, or worry about non-temporal stores).

**Comment by alheinecke** [comment]
This is col-major here, so it's naturally cache-blocked according to first entry in this issue, so really just a loop over N to force the micro kernel to walk all M.

**Comment by mlohry** [comment]
> For the PyFR case, we pulled the N loop outside of the kernel, as we block internally over N and M: https://github.com/libxsmm/libxsmm/blob/master/src/libxsmm_fsspmdm.c#L458 That should help here as well, so it would be great if you could try this.
> 
> In fact I would try to block N%6 == 0, then you get a nice micro kernel on X86 and even ARM :-) But also nb=25 or 50 should fine you case...

So I took m=k=27 and ran this test varying the block size  / stride and looping through N. Serial shows no benefit, but MPI has a huge benefit:

![image](https://user-images.githubusercontent.com/2199374/179013934-cb4b07c8-409d-49d7-addc-922aebac9fa6.png)

Very interesting, thanks!

> Although, really, you want to do what we did in PyFR and cache block your data structure

Clever idea, I'll have to see about prototyping this.

**Comment by FreddieWitherden** [comment]
> > Although, really, you want to do what we did in PyFR and cache block your data structure
> 
> Clever idea, I'll have to see about prototyping this.

Are you padding at all so that the leading dimension is a multiple of the vector length?  This is the big issue that we found with column major; for good performance you need padding.  But this results in quite a bit of waste, especially as vector lengths increase.  Even more perniciously you have to add internal padding to your operators (divergence, for example, as you want f_x, f_y and f_z to be vector-aligned so can't just vertically stack them but have to stack them with padding, which forces interior zeros into your A matrix).

**Comment by mlohry** [comment]
Nope, no padding. Out of curiosity, do you know what fraction of time PyFR is spending in these dense block operations versus the plain blas1-esque flat loops? Is all the kernel fusion wizardry getting you a much higher percentage of time in GEMM-like operations than the "naive" approach?

**Comment by alheinecke** [comment]
@FreddieWitherden : Padding is not needed when wanting good performance for the streaming case. You loose 20% due to the cache-line splits, so when doing blocking of the entire math into caches, was this will cause a performance drop, but it should be more than 20% compared to the padded cases. Note the 20% don't incl SIMD in-efficiencies (27/32 in this case), it's purely from the fact that we have CL splits.

**Comment by FreddieWitherden** [comment]
> Out of curiosity, do you know what fraction of time PyFR is spending in these dense block operations versus the plain blas1-esque flat loops?

It varies depending on the order, element type, and if anti-aliasing is on or not.  Key thing is to exploit sparsity in hexes and prisms as otherwise you'll spend a massive amount of time doing GEMM's.  Everything up to p = 6 is pretty well optimised, and we tend to spent more time in GEMMs as the order increases.

@alheinecke Don't forget the cost from not being able to use streaming stores in the Beta = 0 case.

**Comment by mlohry** [comment]
>It varies depending on the order, element type, and if anti-aliasing is on or not.

In maDG on CPU I see like 25-50% time in GEMM for P2-P4 in explicit, with all tets and anti-aliasing. Much lower on GPU. I never run explicit for real problems though, so the fully implicit shifts the metrics a bit.

>Key thing is to exploit sparsity in hexes and prisms as otherwise you'll spend a massive amount of time doing GEMM's. 

Interesting, thanks Prof. I'll look into that. I've mostly focused on simplices.

**Comment by mlohry** [comment]
@alheinecke is there a programmatic way to determine an optimal block stride one should use over N based on M and K? I assume this must be based on cache size of the CPU.

**Comment by alheinecke** [comment]
It would be great, if you could share you reproducer. I feel something is not right here. While adding Float8 functionality to libxsmm, I saw that we flipped the outer M/N blocking in the kernel ~1.5 years back, totally forgot about this, to allow for better dynamic register blocking. However, this also means, when I go to samples/xgemm and run
`LIBXSMM_VERBOSE=-1 ./kernel 27 30000 27 27 27 27 1 1 0 0 0 0 nopf DP nobr 1 0 10000`
vs.
`LIBXSMM_VERBOSE=-1 ./kernel 27 30 27 27 27 27 1 1 0 0 0 0 nopf DP nobr 1 0 10000`
I get identical code (module the N loop count, which is outside, so it shouldn't matter if that is inside or outside of the assembly block). This can be easily seen when inspecting the corresponding raw bytecode files:
`libxsmm_abi1_clx_f64_nn_27x30x27_27_27_27_a1_b1_p0_br0_uh0_si0_tc-abid_avnni0_bvnni0_cvnni0.mxm` and `libxsmm_abi1_clx_f64_nn_27x30000x27_27_27_27_a1_b1_p0_br0_uh0_si0_tc-abid_avnni0_bvnni0_cvnni0.mxm` .
That also means the blocking you are doing in N shouldn't yield anything.

**Comment by mlohry** [comment]
So you are right, of course. There was an error in my MPI benchmarks. I'm using the excellent celero microbenchmarking library, and that has a parameter for the number of iterations in a test which if set to 0, it does some samples to determine how many are needed to be statistically significant. In an MPI context that meant different processes could have slightly different numbers of runs.

I'm now seeing the regular call getting the same speeds as the manual blocking through N. On the positive side now I'm seeing xsmm never being worse than MKL for any of the sizes tested. About 20% faster at N 27.

**Comment by mlohry** [comment]
Closing as the initial question answered -- thanks!
