### ISSUE TITLE
`libxsmm_cpuid_dot_pack_factor` in x86-specific source file

### ISSUE THREAD

**Issue by rengolin** [libxsmm/libxsmm#770]
Generic function `libxsmm_cpuid_dot_pack_factor` declared in a generic header https://github.com/libxsmm/libxsmm/blob/main_stable/include/libxsmm_cpuid.h#L88 and which implements both Arm and x86 is implemented in x86-specific source file https://github.com/libxsmm/libxsmm/blob/main_stable/src/libxsmm_cpuid_x86.c#L521

Shouldn't it be in a generic source too?

**Comment by hfp** [comment]
Ok, we have polite separation between translation units wrt archs/platforms but sometimes "x86" is "primary" like serving some generics (specifically the case for CPUID). This is because of reducing dependencies are to hold back an almost empty translation unit for a whatsoever generic case.

**Comment by hfp** [comment]
I am closing this issue for above reasons. However, a future revision of LIBXSMM's CPUID (potentially based on orthogonal feature bits) will consider this report.

Since the term "CPUID" can draw attention, it is restated: LIBXSMM uses only ISA feature bits to determine CPUID (no vendor check) plus the execution target can be forced at user's will up to (and including) `SIGILL`.
