### ISSUE TITLE
F64 RCP/RSQRT Eltwise test are failing

### ISSUE THREAD

**Issue by alheinecke** [libxsmm/libxsmm#811]
With: https://github.com/libxsmm/libxsmm/commit/051ac124629124a3c5d87f78351c996874c07ee9

the check-norm calculation changed which leads to major issues with reciprocals (with are only 28bit instead of 54bit for FP43). I have added the old norms:

```
diff --git a/samples/eltwise/eltwise_unary_simple.c b/samples/eltwise/eltwise_unary_simple.c
index 2ec3b7dfa..d24c76160 100644
--- a/samples/eltwise/eltwise_unary_simple.c
+++ b/samples/eltwise/eltwise_unary_simple.c
@@ -605,6 +605,7 @@ int test_unary_op( const libxsmm_blasint M, const libxsmm_blasint N, const libxs
   printf("L2 rel.error  : %.24f\n", norms_out.l2_rel);
   printf("Linf abs.error: %.24f\n", norms_out.linf_abs);
   printf("Linf rel.error: %.24f\n", norms_out.linf_rel);
+  printf("Check-norm (o): %.24f\n", norms_out.normf_rel);
   check_norm = libxsmm_matdiff_epsilon(&norms_out);
   printf("Check-norm    : %.24f\n\n", check_norm);
```

and here is one of the pathological cases:
```
Check-norm (o): 0.000026310733587602566858
Check-norm    : 0.003054283766758906018546
```
(i see even from time to time 0.1). 

We cannot crank up the error bar to these levels. What is the math in the new norm which leads to so off the rails results?

**Comment by hfp** [comment]
Indeed, `libxsmm_matdiff_epsilon` is practically `normf_rel`, but contains/abstracts this norm instead of hard-coding it. We have cases with relative and absolute errors being small (and potentially below threshold/margin), but totally different distribution of respective noise. The `normf_rel` is a relative error-measure which is already not very obvious, and we discussed this (and then agreed on) years ago. Best case for `normf_rel` is linear algebra or particularly BLAS related work which is somewhat settled with the Froebenius (matrix-)norm. To "fix" aforementioned case about small relative and small absolute errors for input with small magnitude, I am essentially dividing `normf_rel` by the coefficient of determination or "R squared" (`rsq`). Imagine a two matrices A and B (can degenerate to vectors), with noise below margin, then `rsq` may disagree (`0`) for A and B being equal aka different distribution of below-threshold-values. The `rsq` is practically `1` for two matrices (... degenerated) with similar value-distribution. The `rsq` helps us to disagree on "gold" vs "test" if all-small values are always in different locations.

**Comment by alheinecke** [comment]
but was is the fix, it sounds to me we are using the wrong norm.

**Comment by hfp** [comment]
> but was is the fix, it sounds to me we are using the wrong norm.

I mean dividing by non-zero rsq should be fine and just emphasize/increase a small normf_rel. It is not too easy to judge the case about "A and B are different" if A and B are matrices (consist of MxN values) based on a single number.

**Comment by hfp** [comment]
Beside of our sophisticated error measures (and actually using Kahan-compensated reductions), a lot of issues can stem from generating artificial input. If one normalizes the input values, they may still carry vastly different orders of magnitudes. The latter can screw up any reduction especially non-compensated reductions.

**Comment by alheinecke** [comment]
My point is the following: we were using Frobenius-Norm before and the inputs are the same as before. Now we change the norm and they are normally the same, but the new norm has spikes where the old one is smooth. Why is the new norm better than Frobenius?
